#ifndef __axz_error_codes__
#define __axz_error_codes__

#include "axz_types.h"

#define AXZ_SUCCESS(code) ( ( ( axz_rc )( code ) ) >= 0 )
#define AXZ_FAILED(code) ( ( (  axz_rc )( code ) ) < 0 )

#define AXZ_OK							0
#define AXZ_OK_STOPPED					1
#define AXZ_OK_REPLACED					2
#define AXZ_OK_SHOULD_STOP				3
#define AXZ_OK_SHOULD_WAIT				4
#define AXZ_OK_IN_PROGRESS				5
#define AXZ_OK_IGNORE   				6

#define AXZ_OK_RANGE_UPDATE_CHECKER    100
#define AXZ_OK_UC_VERSION_FETCHED      AXZ_OK_RANGE_UPDATE_CHECKER + 1
#define AXZ_OK_UC_PACKAGE_READY        AXZ_OK_RANGE_UPDATE_CHECKER + 2

#define AXZ_ERROR_RANGE_COMMON			0
#define AXZ_ERROR_RANGE_JSON            -350
#define AXZ_ERROR_RANGE_WSS             -400
#define AXZ_ERROR_RANGE_HTTPS           -600
#define AXZ_ERROR_RANGE_UPDATE_CHECKER  -800
#define AXZ_ERROR_RANGE_SUBMIT_LOG      -900  
#define AXZ_ERROR_RANGE_CROSS_DOMAIN    -1000
#define AXZ_ERROR_RANGE_TRAY_APP        -1200
#define AXZ_ERROR_RANGE_FD              -1300
#define AXZ_ERROR_RANGE_CLOUD           -1400
#define AXZ_ERROR_RANGE_MANAGER         -1500

#define AXZ_ERROR_UNKNOWN					    	AXZ_ERROR_RANGE_COMMON - 1
#define AXZ_ERROR_MEMORY_DRAINED			    	AXZ_ERROR_RANGE_COMMON - 2
#define AXZ_ERROR_NATIVE_API      				    AXZ_ERROR_RANGE_COMMON - 3
#define AXZ_ERROR_OUT_OF_RANGE  					AXZ_ERROR_RANGE_COMMON - 4
#define AXZ_ERROR_ACCESS_DENIED     				AXZ_ERROR_RANGE_COMMON - 5
#define AXZ_ERROR_NOT_FOUND         				AXZ_ERROR_RANGE_COMMON - 6
#define AXZ_ERROR_NOT_SUPPORT    	    			AXZ_ERROR_RANGE_COMMON - 7
#define AXZ_ERROR_NOT_READY     		    		AXZ_ERROR_RANGE_COMMON - 8
#define AXZ_ERROR_INVALID_INPUT				    	AXZ_ERROR_RANGE_COMMON - 9
#define AXZ_ERROR_INVALID_OUTPUT				    AXZ_ERROR_RANGE_COMMON - 10
#define AXZ_ERROR_TIMEOUT   				    	AXZ_ERROR_RANGE_COMMON - 11
#define AXZ_ERROR_ZIP_FAILED    			    	AXZ_ERROR_RANGE_COMMON - 12
#define AXZ_ERROR_UNZIP_FAILED	    		    	AXZ_ERROR_RANGE_COMMON - 13
#define AXZ_ERROR_DUPLICATED                        AXZ_ERROR_RANGE_COMMON - 14
#define AXZ_ERROR_UNREACHABLE                       AXZ_ERROR_RANGE_COMMON - 15
#define AXZ_ERROR_INTERRUPTED                       AXZ_ERROR_RANGE_COMMON - 16
#define AXZ_ERROR_ABORTED                           AXZ_ERROR_RANGE_COMMON - 17
#define AXZ_ERROR_PERMISSION_DENIED                 AXZ_ERROR_RANGE_COMMON - 18
#define AXZ_ERROR_SHARING_VIOLATION                 AXZ_ERROR_RANGE_COMMON - 19
#define AXZ_ERROR_CREATE_SERVICE_FAILED             AXZ_ERROR_RANGE_COMMON - 20
#define AXZ_ERROR_OPEN_SERVICE_FAILED               AXZ_ERROR_RANGE_COMMON - 21
#define AXZ_ERROR_START_SERVICE_FAILED              AXZ_ERROR_RANGE_COMMON - 22
#define AXZ_ERROR_STOP_SERVICE_FAILED               AXZ_ERROR_RANGE_COMMON - 23
#define AXZ_ERROR_DELETE_SERVICE_FAILED             AXZ_ERROR_RANGE_COMMON - 24
#define AXZ_ERROR_SET_SERVICE_DESC_FAILED           AXZ_ERROR_RANGE_COMMON - 25
#define AXZ_ERROR_OPEN_SCM_FAILED                   AXZ_ERROR_RANGE_COMMON - 26


#define AXZ_ERROR_JSON_FORMAT_INVALID			    AXZ_ERROR_RANGE_JSON - 1
#define AXZ_ERROR_JSON_KEY_MISSED	    			AXZ_ERROR_RANGE_JSON - 2

#define AXZ_ERROR_WSS_CONTEXT_CREATION_FAILED       AXZ_ERROR_RANGE_WSS - 1
#define AXZ_ERROR_WSS_CONNECTION_FAILED             AXZ_ERROR_RANGE_WSS - 2
#define AXZ_ERROR_WSS_CONNECTION_CLOSED             AXZ_ERROR_RANGE_WSS - 3

#define AXZ_ERROR_MANAGER_CONFIG_MISSED             AXZ_ERROR_RANGE_MANAGER - 1
#define AXZ_ERROR_MANAGER_INVALID_CONFIG            AXZ_ERROR_RANGE_MANAGER - 2

#define AXZ_ERROR_FC_SDK_SETUP_FAILED                   AXZ_ERROR_RANGE_FD - 1
#define AXZ_ERROR_FC_SDK_INVOKE_FAILED                  AXZ_ERROR_RANGE_FD - 2
#define AXZ_ERROR_FC_TYPE_CHECKED_UNKOWN                AXZ_ERROR_RANGE_FD - 3
#define AXZ_ERROR_FC_TYPE_CHECK_FAILED                  AXZ_ERROR_RANGE_FD - 4
#define AXZ_ERROR_FC_ACTION_ID_PARSE_FAILED             AXZ_ERROR_RANGE_FD - 5
#define AXZ_ERROR_FC_ACTION_CATEGORY_UNKOWN             AXZ_ERROR_RANGE_FD - 6
#define AXZ_ERROR_FC_AGENT_ACTION_UNKOWN                AXZ_ERROR_RANGE_FD - 7
#define AXZ_ERROR_FC_ACTION_CHAIN_EMPTY                 AXZ_ERROR_RANGE_FD - 8
#define AXZ_ERROR_FC_RESULT_ARRAY_UNSEEN                AXZ_ERROR_RANGE_FD - 9
#define AXZ_ERROR_FC_ARGUMENT_FORMAT_WRONG              AXZ_ERROR_RANGE_FD - 10
#define AXZ_ERROR_FC_ARGUMENT_CONVERTION_FAILED         AXZ_ERROR_RANGE_FD - 11


#define AXZ_ERROR_HTTPS_UNKNOWN_VERB                    AXZ_ERROR_RANGE_HTTPS - 1
#define AXZ_ERROR_HTTPS_INVALID_HEADERS                 AXZ_ERROR_RANGE_HTTPS - 2
#define AXZ_ERROR_HTTPS_BODY_MISSED                     AXZ_ERROR_RANGE_HTTPS - 3
#define AXZ_ERROR_HTTPS_SINGLE_TRANSFER_FAILED          AXZ_ERROR_RANGE_HTTPS - 4
#define AXZ_ERROR_HTTPS_RESOLVE_PROXY_FAILED            AXZ_ERROR_RANGE_HTTPS - 5
#define AXZ_ERROR_HTTPS_RESOLVE_HOST_FAILED             AXZ_ERROR_RANGE_HTTPS - 6
#define AXZ_ERROR_HTTPS_CONNECT_FAILED                  AXZ_ERROR_RANGE_HTTPS - 7
#define AXZ_ERROR_HTTPS_UNKOWN_SERVER_RESPONSE          AXZ_ERROR_RANGE_HTTPS - 8

#define AXZ_ERROR_LS_ZIP_LOG_FAILED                     AXZ_ERROR_RANGE_SUBMIT_LOG - 1
#define AXZ_ERROR_LS_UPLOAD_LOG_FAILED                  AXZ_ERROR_RANGE_SUBMIT_LOG - 2
#define AXZ_ERROR_LS_POST_ZENDESK_FAILED                AXZ_ERROR_RANGE_SUBMIT_LOG - 3

#define AXZ_ERROR_CLD_TOKEN_GET_FAILED                  AXZ_ERROR_RANGE_CLOUD - 1

#endif
