set(JAS_PRECOMPILE_HEADERS
    <algorithm>
    <ctime>
    <functional>
    <iomanip>
    <list>
    <map>
    <regex>
    <set>
    <sstream>
    <string>
    <string_view>
    <unordered_map>
    <unordered_set>
    <vector>
    <memory>
    <algorithm>
    "include/jas/Json.h"
    "include/jas/String.h"
    )
